#!/bin/bash
# Feni Hotel - Facility Server Installation Script
# This script automates the deployment of a new facility server on Ubuntu 22.04 LTS.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}==============================================${NC}"
echo -e "${GREEN}   Feni Hotel - Facility Server Installer     ${NC}"
echo -e "${GREEN}==============================================${NC}"

# 1. Ensure running as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root (using sudo)${NC}"
  exit 1
fi

echo -e "${YELLOW}Step 1: Installing System Dependencies...${NC}"
apt update && apt upgrade -y
apt install -y docker.io docker-compose avahi-daemon avahi-utils openssl jq curl

systemctl enable docker avahi-daemon
systemctl start docker avahi-daemon

echo -e "${GREEN}Dependencies installed successfully.${NC}"

# 2. GHCR Authentication
echo -e "${YELLOW}Step 2: GitHub Container Registry Authentication${NC}"
echo -e "You need a GitHub Personal Access Token (PAT) with 'read:packages' scope."
read -p "GitHub Username: " GITHUB_USERNAME
read -s -p "GitHub PAT: " GITHUB_PAT
echo ""

echo -e "Authenticating Docker with ghcr.io..."
echo "$GITHUB_PAT" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin || {
    echo -e "${RED}Docker login failed! Please check your credentials.${NC}"
    exit 1
}

echo -e "${GREEN}Successfully authenticated with ghcr.io.${NC}"

# 3. Setup Directory
INSTALL_DIR="/opt/feni-hotel"
echo -e "${YELLOW}Step 3: Setting up Installation Directory ($INSTALL_DIR)...${NC}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# 4. Configuration
echo -e "${YELLOW}Step 4: Configuration Setup${NC}"
echo "Generating secure JWT secret..."
JWT_SECRET=$(openssl rand -base64 32)

echo -e "Please provide the following configuration details:"
read -s -p "Admin Account Bootstrap Password: " BOOTSTRAP_ADMIN_PASSWORD
echo ""
read -p "Cloud API URL (e.g., https://app.senforge.com): " CLOUD_API_URL
read -s -p "Cloud API Key: " CLOUD_API_KEY
echo ""
read -p "Optional: Gmail Sender Address (leave blank to skip): " GMAIL_SENDER_ADDRESS
if [ -n "$GMAIL_SENDER_ADDRESS" ]; then
    read -s -p "Gmail App Password: " GMAIL_APP_PASSWORD
    echo ""
else
    GMAIL_APP_PASSWORD=""
fi

# Write .env file
echo "Writing .env file..."
cat > .env <<EOF
# Auto-generated by install.sh on $(date)
# -----------------------------
# REQUIRED: JWT & Security
# -----------------------------
JWT_SECRET=${JWT_SECRET}
BOOTSTRAP_ADMIN_PASSWORD=${BOOTSTRAP_ADMIN_PASSWORD}

# -----------------------------
# REQUIRED: Cloud Sync
# -----------------------------
CLOUD_API_URL=${CLOUD_API_URL}
CLOUD_API_KEY=${CLOUD_API_KEY}

# -----------------------------
# OPTIONAL: Email (Gmail SMTP)
# -----------------------------
GMAIL_SENDER_ADDRESS=${GMAIL_SENDER_ADDRESS}
GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
EOF

# 5. Docker Compose file
echo "Writing docker-compose.yml..."
cat > docker-compose.yml <<'EOF'
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: feni-postgres
    environment:
      POSTGRES_DB: feni_hotel
      POSTGRES_USER: feni_user
      POSTGRES_PASSWORD: feni_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: feni-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    image: ghcr.io/mikedalu/feni-hotel-backend:latest
    container_name: feni-backend
    env_file: 
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/feni_hotel
      - SPRING_DATASOURCE_USERNAME=feni_user
      - SPRING_DATASOURCE_PASSWORD=feni_password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    volumes:
      - feni_uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    image: ghcr.io/mikedalu/feni-hotel-frontend:latest
    container_name: feni-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  feni_uploads:
EOF

echo -e "${GREEN}Configuration files created successfully.${NC}"

# 6. Start the server
echo -e "${YELLOW}Step 5: Pulling images and starting the server...${NC}"
docker-compose pull
docker-compose up -d

echo -e "${GREEN}==============================================${NC}"
echo -e "${GREEN}   Installation Completed Successfully!       ${NC}"
echo -e "${GREEN}==============================================${NC}"
echo -e "You can now access the Feni Hotel system from any device on this network:"
echo -e "- Frontend Dashboard: http://hotel-hub.local"
echo -e "- Backend API Docs:   http://hotel-hub.local:8080/swagger-ui.html"
echo -e ""
echo -e "Log in with username: ${YELLOW}admin${NC} and the password you provided."
echo -e "You will be prompted to reset the password immediately upon first login."
echo -e "Check the logs using: ${YELLOW}cd $INSTALL_DIR && docker-compose logs -f${NC}"
