<#
.SYNOPSIS
Feni Hotel - Windows Facility Server Installation Script

.DESCRIPTION
This script automates the deployment of a new facility server on Windows 10/11 Pro 
assuming Docker Desktop is installed.
#>

$ErrorActionPreference = "Stop"

Write-Host "==============================================" -ForegroundColor Green
Write-Host "   Feni Hotel - Facility Server Installer     " -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green

# 1. Ensure running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "Please run this script as Administrator. Right-click PowerShell and select 'Run as Administrator'." -ForegroundColor Red
    exit
}

# 2. Check for Docker
Write-Host "Step 1: Checking System Dependencies..." -ForegroundColor Yellow
if (-not (Get-Command "docker" -ErrorAction SilentlyContinue)) {
    Write-Host "Docker is not installed or not in your PATH. Please install Docker Desktop before continuing." -ForegroundColor Red
    exit
}

if (-not (Get-Command "docker-compose" -ErrorAction SilentlyContinue)) {
    Write-Host "docker-compose is not installed. Ensure Docker Desktop is fully updated." -ForegroundColor Red
    exit
}

# Ensure docker daemon is running
try {
    $null = docker info
} catch {
    Write-Host "Docker daemon is not running. Please start Docker Desktop and try again." -ForegroundColor Red
    exit
}

Write-Host "Dependencies verified successfully." -ForegroundColor Green
Write-Host ""

# 3. GHCR Authentication
Write-Host "Step 2: GitHub Container Registry Authentication" -ForegroundColor Yellow
Write-Host "You need a GitHub Personal Access Token (PAT) with 'read:packages' scope."
$GitHubUsername = Read-Host "GitHub Username"
$GitHubPAT = Read-Host "GitHub PAT" -AsSecureString

$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($GitHubPAT)
$PATString = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)

Write-Host "Authenticating Docker with ghcr.io..."
$PATString | docker login ghcr.io -u "$GitHubUsername" --password-stdin
if ($LASTEXITCODE -ne 0) {
    Write-Host "Docker login failed! Please check your credentials." -ForegroundColor Red
    exit
}

Write-Host "Successfully authenticated with ghcr.io." -ForegroundColor Green
Write-Host ""

# 4. Setup Directory
$InstallDir = "C:\feni-hotel"
Write-Host "Step 3: Setting up Installation Directory ($InstallDir)..." -ForegroundColor Yellow
if (-not (Test-Path -Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir | Out-Null
}
Set-Location -Path $InstallDir

# 5. Configuration
Write-Host "Step 4: Configuration Setup" -ForegroundColor Yellow
Write-Host "Generating secure JWT secret..."
$RandomBytes = New-Object Byte[] 32
$Rand = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$Rand.GetBytes($RandomBytes)
$JwtSecret = [Convert]::ToBase64String($RandomBytes)

Write-Host "Please provide the following configuration details:"
$BootstrapAdminPassword = Read-Host "Admin Account Bootstrap Password" -AsSecureString
$AdminPasswordString = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($BootstrapAdminPassword))

$CloudApiUrl = Read-Host "Cloud API URL (e.g., https://app.senforge.com)"
$CloudApiKey = Read-Host "Cloud API Key" -AsSecureString
$CloudApiKeyString = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($CloudApiKey))

$GmailSenderAddress = Read-Host "Optional: Gmail Sender Address (leave blank to skip)"
$GmailAppPasswordString = ""
if ($GmailSenderAddress) {
    $GmailAppPassword = Read-Host "Gmail App Password" -AsSecureString
    $GmailAppPasswordString = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($GmailAppPassword))
}

Write-Host "Writing .env file..."
$EnvContent = @"
# Auto-generated by install.ps1 on $(Get-Date)
# -----------------------------
# REQUIRED: JWT & Security
# -----------------------------
JWT_SECRET=$JwtSecret
BOOTSTRAP_ADMIN_PASSWORD=$AdminPasswordString

# -----------------------------
# REQUIRED: Cloud Sync
# -----------------------------
CLOUD_API_URL=$CloudApiUrl
CLOUD_API_KEY=$CloudApiKeyString

# -----------------------------
# OPTIONAL: Email (Gmail SMTP)
# -----------------------------
GMAIL_SENDER_ADDRESS=$GmailSenderAddress
GMAIL_APP_PASSWORD=$GmailAppPasswordString
"@

Set-Content -Path ".env" -Value $EnvContent -Encoding UTF8

Write-Host "Writing docker-compose.yml..."
$DockerComposeContent = @"
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: feni-postgres
    environment:
      POSTGRES_DB: feni_hotel
      POSTGRES_USER: feni_user
      POSTGRES_PASSWORD: feni_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: feni-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    image: ghcr.io/mikedalu/feni-hotel-backend:latest
    container_name: feni-backend
    env_file: 
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/feni_hotel
      - SPRING_DATASOURCE_USERNAME=feni_user
      - SPRING_DATASOURCE_PASSWORD=feni_password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    volumes:
      - feni_uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    image: ghcr.io/mikedalu/feni-hotel-frontend:latest
    container_name: feni-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  feni_uploads:
"@

Set-Content -Path "docker-compose.yml" -Value $DockerComposeContent -Encoding UTF8

Write-Host "Configuration files created successfully." -ForegroundColor Green
Write-Host ""

# 6. Start the server
Write-Host "Step 5: Pulling images and starting the server..." -ForegroundColor Yellow
docker-compose pull
docker-compose up -d

Write-Host "==============================================" -ForegroundColor Green
Write-Host "   Installation Completed Successfully!       " -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green
Write-Host "You can now access the Feni Hotel system from any device on this network:"
Write-Host "- Frontend Dashboard: http://localhost"
Write-Host "- Backend API Docs:   http://localhost:8080/swagger-ui.html"
Write-Host ""
Write-Host "Note: For other devices to access this server, they should navigate to this PC's IP address (e.g., http://192.168.1.100)." -ForegroundColor Cyan
Write-Host ""
Write-Host "Log in with username: admin and the password you provided." -ForegroundColor Yellow
Write-Host "You will be prompted to reset the password immediately upon first login."
Write-Host "Check the logs using: cd $InstallDir ; docker-compose logs -f"
